=== oleksapanchuk/tax/xml/user.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="root">
        <xsd:complexType>
            <xsd:sequence>

                <xsd:element name="user" minOccurs="0" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>

                            <xsd:element name="id_user">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:int">
                                        <xsd:minInclusive value="1"/>
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>

                            <xsd:element name="first_name">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string">
                                        <xsd:pattern value="[A-ZА-Я][a-zа-я]*"/>
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>

                            <xsd:element name="last_name">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string">
                                        <xsd:pattern value="[a-zA-Zа-яіА-Я]+([ '-][a-zA-Zіа-яА-Я]+)*"/>
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>

                            <xsd:element name="email">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string">
                                        <xsd:pattern value="\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*"/>
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>

                            <xsd:element name="taxes">
                                <xsd:complexType>
                                    <xsd:sequence>

                                        <xsd:element name="tax"  minOccurs="0" maxOccurs="unbounded">
                                            <xsd:complexType>

                                                <xsd:simpleContent>
                                                    <xsd:restriction base="xsd:decimal">
                                                        <xsd:minInclusive value="0"/>
                                                        <xsd:attribute name="idTax" use="required">
                                                            <xsd:simpleType>
                                                                <xsd:restriction base="xsd:int">
                                                                    <xsd:enumeration value="1"/>
                                                                    <xsd:enumeration value="2"/>
                                                                    <xsd:enumeration value="3"/>
                                                                    <xsd:enumeration value="4"/>
                                                                    <xsd:enumeration value="5"/>
                                                                    <xsd:enumeration value="6"/>
                                                                    <xsd:enumeration value="7"/>
                                                                </xsd:restriction>
                                                            </xsd:simpleType>
                                                        </xsd:attribute>
                                                    </xsd:restriction>
                                                </xsd:simpleContent>

                                            </xsd:complexType>
                                        </xsd:element>

                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>

                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>

            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

</xsd:schema>

=== oleksapanchuk/tax/xml/user.xml
<?xml version="1.0" encoding="UTF-8" ?>

<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xml/user.xsd">

    <user>
        <id_user>1</id_user>
        <first_name>Катерина</first_name>
        <last_name>Кондратюк</last_name>
        <email>catrinnn@gmail.com</email>
        <taxes>
            <tax idTax="1">6500.0</tax>
            <tax idTax="5">3000</tax>
        </taxes>
    </user>

    <user>
        <id_user>11</id_user>
        <first_name>Богдан</first_name>
        <last_name>Карасійчук</last_name>
        <email>bodichkakar@gmail.com</email>
        <taxes>
            <tax idTax="3">300</tax>
            <tax idTax="7">40</tax>
            <tax idTax="2">400</tax>
        </taxes>
    </user>

</root>
